const assert = require('assert');
const {
  Snake,
  oldestFoodKey,
  findShortestPath,
  isAdjacent,
  calculateGrowth,
  collectDueRecoveries,
  runSimulation,
  CONTRIBUTION_RECOVERY_INTERVAL_STEPS,
  DEFAULT_SIMULATION_OPTIONS,
} = require('./gameEngine');
const {
  contributionPointsForDay,
} = require('./contributionData');

function testOldestFoodSelection() {
  const foods = new Set(['1,1', '2,2', '3,3']);
  const spawnOrders = new Map([
    ['1,1', 8],
    ['2,2', 3],
    ['3,3', 5],
  ]);
  assert.strictEqual(oldestFoodKey(foods, spawnOrders), '2,2');
}

function testContributionLevelWeightsAndGrowth() {
  assert.strictEqual(contributionPointsForDay({ contributionCount: 1, contributionLevel: 'FIRST_QUARTILE' }), 1);
  assert.strictEqual(contributionPointsForDay({ contributionCount: 1, contributionLevel: 'SECOND_QUARTILE' }), 2);
  assert.strictEqual(contributionPointsForDay({ contributionCount: 1, contributionLevel: 'THIRD_QUARTILE' }), 3);
  assert.strictEqual(contributionPointsForDay({ contributionCount: 1, contributionLevel: 'FOURTH_QUARTILE' }), 4);
  assert.strictEqual(contributionPointsForDay({ contributionCount: 1, color: '#9be9a8' }), 1);
  assert.strictEqual(contributionPointsForDay({ contributionCount: 1, color: '#39d353' }), 4);
  assert.strictEqual(contributionPointsForDay({ contributionCount: 1, color: '#abcdef' }), 1);
  assert.strictEqual(contributionPointsForDay({ contributionCount: 0, contributionLevel: 'FOURTH_QUARTILE' }), 0);

  let growth = calculateGrowth(0, 4, 4);
  assert.deepStrictEqual(growth, { grewBy: 1, progress: 0 }, 'one More contribution must grow one segment');

  let progress = 0;
  let totalGrowth = 0;
  for (let index = 0; index < 4; index++) {
    growth = calculateGrowth(progress, 1, 4);
    progress = growth.progress;
    totalGrowth += growth.grewBy;
    assert.strictEqual(growth.grewBy, index === 3 ? 1 : 0);
  }
  assert.strictEqual(totalGrowth, 1, 'four Less contributions must grow exactly one segment');
  assert.strictEqual(progress, 0);
}

function testSnakeLengthCap() {
  const snake = new Snake(0, 2, { dr: 0, dc: 1 }, 3, 5);
  assert.strictEqual(snake.grow(10), 2);
  assert.strictEqual(snake.targetLength, 5);
  assert.strictEqual(snake.maximumLength, 5);
  assert.strictEqual(snake.grow(1), 0, 'growth must stop at the contribution-day cap');
}

function testIndependentSimultaneousRecoveryTimers() {
  const original = new Set(['1,1', '2,2', '3,3']);
  const foods = new Set();
  const eatenSteps = new Map([
    ['1,1', 10],
    ['2,2', 10],
    ['3,3', 20],
  ]);
  const snake = {
    minimumLength: 3,
    body: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
    ],
  };

  assert.deepStrictEqual(
    collectDueRecoveries(original, foods, eatenSteps, snake, 44, 35),
    { generatedKeys: [], droppedKeys: [], autoGeneratedKeys: [] },
    'no contribution should recover before its own 35-step timer expires',
  );

  assert.deepStrictEqual(
    collectDueRecoveries(original, foods, eatenSteps, snake, 45, 35),
    {
      generatedKeys: ['1,1', '2,2'],
      droppedKeys: [],
      autoGeneratedKeys: ['1,1', '2,2'],
    },
    'all contributions whose independent timers expire together must recover together',
  );

  eatenSteps.set('1,2', 10);
  original.add('1,2');
  snake.body = [
    { row: 0, col: 0 },
    { row: 0, col: 1 },
    { row: 1, col: 1 },
    { row: 1, col: 2 },
  ];
  assert.deepStrictEqual(
    collectDueRecoveries(original, foods, eatenSteps, snake, 45, 35),
    {
      generatedKeys: ['1,1', '1,2', '2,2'],
      droppedKeys: ['1,2'],
      autoGeneratedKeys: ['1,1', '2,2'],
    },
    'a due tail should drop once while every other due cell recovers in the same batch',
  );
}

function testOldestTargetAndRestrictedRecovery() {
  const contributions = new Set([
    '0,35',
    '1,35',
    '2,35',
    '6,39',
    '4,49',
    '5,49',
  ]);
  const options = {
    ...DEFAULT_SIMULATION_OPTIONS,
    contributionWeights: new Map([
      ['0,35', 1],
      ['1,35', 1],
      ['2,35', 1],
      ['6,39', 1],
      ['4,49', 2],
      ['5,49', 4],
    ]),
    gridRows: 7,
    gridCols: 54,
    simulationFile: null,
  };
  assert.strictEqual(
    options.dropInterval,
    CONTRIBUTION_RECOVERY_INTERVAL_STEPS,
    'the default recovery interval must use the configured slow interval',
  );
  const { frames, snake } = runSimulation(contributions, options);

  let eatEvents = 0;
  let autoRecoveryEvents = 0;
  let generatedEvents = 0;
  let autoShrinkEvents = 0;

  assert(
    frames.length * options.frameDelayMs >= 60_000,
    'the SVG frame sequence must last at least one minute',
  );
  assert.strictEqual(frames.at(-1).cumulativeSteps, options.minimumSteps);

  for (let index = 0; index < frames.length; index++) {
    const frame = frames[index];
    const expectedOldest = oldestFoodKey(frame.foodSet, frame.foodSpawnOrders);
    assert.strictEqual(frame.targetKey, expectedOldest, `frame ${index} does not expose the oldest food as target`);

    for (const key of frame.foodSet) {
      assert(contributions.has(key), `food generated outside an original contribution cell: ${key}`);
    }

    const bodyKeys = frame.snakeBody.map(({ row, col }) => `${row},${col}`);
    assert.strictEqual(new Set(bodyKeys).size, bodyKeys.length, `snake overlaps itself in frame ${index}`);

    if (index === 0) continue;
    const previous = frames[index - 1];
    const stepDelta = frame.cumulativeSteps - previous.cumulativeSteps;

    if (stepDelta === 1) {
      assert(isAdjacent(previous.snakeBody[0], frame.snakeBody[0]), `invalid move in frame ${index}`);
      assert.strictEqual(
        frame.moveTargetKey,
        oldestFoodKey(previous.foodSet, previous.foodSpawnOrders),
        `movement in frame ${index} did not target the oldest food`,
      );

      if (frame.moveTargetKey) {
        const fakeSnake = {
          body: previous.snakeBody,
          targetLength: previous.snakeBody.length,
          direction: previous.snakeDirection,
          head: previous.snakeBody[0],
        };
        const shortestPath = findShortestPath(
          fakeSnake,
          frame.moveTargetKey,
          options.gridRows,
          options.gridCols,
        );
        if (shortestPath && shortestPath.length > 0) {
          assert.deepStrictEqual(
            frame.snakeBody[0],
            shortestPath[0],
            `movement in frame ${index} did not take a shortest safe step`,
          );
        }
      }
    } else {
      assert.strictEqual(stepDelta, 0, `unexpected step jump in frame ${index}`);
      assert(
        frame.generatedKey || frame.autoShrinkBy,
        `only a generation or natural shrink event may create a zero-step frame (${index})`,
      );
    }

    if (frame.ateKey) {
      eatEvents++;
      assert(previous.foodSet.has(frame.ateKey));
      assert(!frame.foodSet.has(frame.ateKey));
      assert.strictEqual(frame.atePoints, options.contributionWeights.get(frame.ateKey));
      assert.strictEqual(
        frame.snakeBody.length,
        previous.snakeBody.length + frame.grewBy,
        `growth did not match earned contribution points in frame ${index}`,
      );
      assert.strictEqual(
        frame.grewBy,
        Math.floor((previous.growthProgress + frame.atePoints) / options.growthPointsPerSegment),
      );
      assert.strictEqual(
        frame.growthProgress,
        (previous.growthProgress + frame.atePoints) % options.growthPointsPerSegment,
      );
    }

    if (frame.generatedKeys.length > 0) {
      generatedEvents += frame.generatedKeys.length;
      autoRecoveryEvents += frame.autoGeneratedKeys.length;
      assert.strictEqual(frame.generatedKey, frame.generatedKeys[0]);
      assert.strictEqual(frame.droppedKey, frame.droppedKeys[0] || null);
      assert.strictEqual(frame.dropSourceKey, frame.droppedKeys[0] || null);
      assert.strictEqual(
        frame.snakeBody.length,
        previous.snakeBody.length - frame.droppedKeys.length,
      );

      for (const key of frame.generatedKeys) {
        assert(contributions.has(key), `generated outside original contribution cells: ${key}`);
        assert(!previous.foodSet.has(key), `generated over an existing contribution: ${key}`);
        assert(frame.foodSet.has(key));
        const eatenStep = previous.foodEatenSteps.get(key);
        assert(Number.isFinite(eatenStep), `missing independent timer for ${key}`);
        assert(
          frame.cumulativeSteps - eatenStep >= options.dropInterval,
          `${key} recovered before its own ${options.dropInterval}-step timer expired`,
        );
      }

    }

    if (frame.autoShrinkBy) {
      autoShrinkEvents += frame.autoShrinkBy;
      assert.strictEqual(frame.autoShrinkBy, 1);
      assert.strictEqual(frame.cumulativeSteps % options.autoShrinkInterval, 0);
      assert.strictEqual(frame.generatedKeys.length, 0);
      assert.strictEqual(frame.droppedKeys.length, 0);
      assert.strictEqual(frame.foodSet.size, previous.foodSet.size);
      for (const key of frame.foodSet) assert(previous.foodSet.has(key));
      assert.strictEqual(frame.snakeBody.length, previous.snakeBody.length - 1);
    }

    assert(
      frame.snakeBody.length <= contributions.size,
      `snake exceeded the ${contributions.size}-day contribution cap in frame ${index}`,
    );
  }

  assert(eatEvents > 0, 'the snake should eat real contribution points');
  assert(autoRecoveryEvents > 0, 'missing original contribution cells should self-restore');
  assert(autoShrinkEvents > 0, 'the snake should naturally lose one segment every 10 steps');
  assert(
    generatedEvents > contributions.size,
    'total generated contributions must not be capped by the original cell count',
  );
  assert(snake.alive, 'the snake should survive the one-minute simulation');
}

testOldestFoodSelection();
testContributionLevelWeightsAndGrowth();
testSnakeLengthCap();
testIndependentSimultaneousRecoveryTimers();
testOldestTargetAndRestrictedRecovery();

console.log('All game engine regression tests passed.');
